#!/usr/bin/env node

/**
 * Build script for Vercel deployment
 * This script injects environment variables from Vercel into the environment.ts file
 * before building the application.
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('🚀 Starting Vercel build process...');

// Path to environment.ts
const envPath = path.join(__dirname, 'libs/data-access/src/lib/config/environment.ts');

// Read environment variables from Vercel
const GITHUB_TOKEN = process.env.GITHUB_TOKEN || '';
const GITHUB_USERNAME = process.env.GITHUB_USERNAME || 'Yohani95';
const BASE_URL = process.env.BASE_URL || 'https://portafolio-yohani-espinoza.vercel.app';
const FORMSPREE_FORM_ID = process.env.FORMSPREE_FORM_ID || '';

console.log('📝 Environment variables:');
console.log(`   GITHUB_TOKEN: ${GITHUB_TOKEN ? '✅ Set' : '❌ Not set'}`);
console.log(`   GITHUB_USERNAME: ${GITHUB_USERNAME}`);
console.log(`   BASE_URL: ${BASE_URL}`);
console.log(
  `   FORMSPREE_FORM_ID: ${FORMSPREE_FORM_ID ? '✅ Set (' + FORMSPREE_FORM_ID + ')' : '❌ Not set'}`
);

// Generate environment.ts content
const envContent = `// Auto-generated by build-vercel.js
// DO NOT EDIT THIS FILE MANUALLY

export const environment = {
  production: true,
  githubToken: '${GITHUB_TOKEN}',
  githubUsername: '${GITHUB_USERNAME}',
  baseUrl: '${BASE_URL}',
  apiUrl: '${BASE_URL}/api',
  gaTrackingId: '',
  formspreeFormId: '${FORMSPREE_FORM_ID}',
};
`;

try {
  // Write environment.ts
  fs.writeFileSync(envPath, envContent);
  console.log('✅ Environment file updated successfully');

  // Build the application
  console.log('🏗️  Building application...');
  execSync('npm run build', { stdio: 'inherit' });

  console.log('✅ Build completed successfully!');
} catch (error) {
  console.error('❌ Build failed:', error.message);
  process.exit(1);
}
